### ISSUE TITLE
dictionary attack

### ISSUE THREAD

**Issue by sashank** [arisath/Private-Set-Intersection#1]
Is there a paper on the security analysis of the protocol described ? I believe it is semi-honest model because a malicious client could calculate a dictionary of all possible hashes not alone his entries and decrypt everything the server sends ?

**Comment by arisath** [comment]
Hi, thanks for your interest . 

Indeed somebody could attempt to create a rainbow table with  all possible SHA-1 outputs, which is 2^160 different hashes (not  few huh?). But that is a common problem with hashing which is easily preventable by adding some salt bits to the input prior to hashing. 

I hope that helped

**Comment by sashank** [comment]
It depends on the input data type and its possibilities . For example, if  the input data type is 32 bit ip address then malicious client just need to calculate 2^32 Hash values and keep instead of calculating its own entries. If the input is english language then around 10^6 (roughly 2^20 ?) words which is even smaller ? 

Now if we add salt bits to beat this , the client has to do more work . The server could add salt bits per entry and give these salt entries too along with the encrypted data and HMAC's the client should now calculate hashes of its entries with all possible salt values.  

Overall creative work but the overhead of server sending all its entries would be too much in real world.

**Comment by arisath** [comment]
Exactly it depends a lot on the data, in the examples you described, indeed creating a rainbow table is feasible, however it is not feasible for other types of data, e.g. a video. 

I do not think salt adds a significant overhead. The use of salt is very common when it comes to hashing, for example every time you register on a website your password is salted and hashed, then every time you attempt to log in, your salt is retrieved and appended to your input password before hashed and compared with the password stored in the DB.

Now regarding the part that sending all the entries would be too much, with all the respect I would have to disagree. Real life applications are using similar protocols, take for example the WhatsUp and Viber applications, they use similar protocols to identify which of your contracts are using Viber and WhatsUp.
Do not forget that you send the hashes (160bits/entry) not the entry itself.

**Comment by sashank** [comment]
Makes sense .
